### ISSUE TITLE
Move STATICLIB defines out of the source code and into project settings

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetHelper#1]
I was unsuccessful compiling the source code when attempting to place the following defines inside the project file. Likely operator error on my part.

Within miniupnpc_declspec.h
``` C
#define MINIUPNP_STATICLIB
```

Within natpmp_declspec.h
``` C
#define NATPMP_STATICLIB
```

-Brett

**Comment by DanRStevens** [comment]
Hmm, that is rather curious. Can you elaborate on any error or warning messages during compilation? Is there a difference when compiling the different project configurations.
