### ISSUE TITLE
Replace MSVC solution configuration ReleaseMinSize with Release

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetHelper#3]
For simplicity sake, I think we want to target a single release and single debug configuration.

Is there any reason to explicitly state MinSize in the configuration type?

**Comment by DanRStevens** [comment]
I assume the duplication in the thread title is a typo.

It was fairly common to have both Release and ReleaseMinSize way back in the day. I don't see much need for it though. That actual release will of course make a decision as to which configuration was used.

Previously, I think there was a bigger difference in size and speed between speed optimizations and space optimizations. Depending on the environment, you might prefer one over the other. Code intended for embedded systems tended to have limited memory, and low processing needs, so they were often optimized for reduced space. High performance modelling or desktop software might have been optimized for speed at the expense of space.

Speed optimizations might have done things like unrolling a loop. In more extreme cases, I've heard examples where the compiler completely unrolled a loop with 512 iterations done for vector or matrix math, which seriously bloats the code, but removes all overhead for loop mechanics, which might dominate for a simple calculation. Though with the memory hierarchy speed differences, and small high-speed cache lines on modern CPUs, some people found optimizing for space actually produced faster results than optimizing for speed. If the loop code completely fits in a high-speed cache line, the result may be faster than trying to stuff 512 x the loop body through the CPU over the slower main memory interface.

All that of course lent itself well to the argument that premature optimization was evil and should be avoided.

----

As for this project, it is neither speed sensitive, not size sensitive. It really doesn't matter if you optimize for speed, or size, or even neither. Feel free to go with default settings if that is convenient.

I support trimming configurations to support a simpler project structure.

**Comment by Brett208** [comment]
Title edited to remove typo as pointed out. The duplicate issue was also closed. GitHub was having database issues when I was working on this so it was causing me a lot of heartache.

@Arklon1 any issue with renaming ReleaseMinSize to just Release

**Comment by DanRStevens** [comment]
I kind of misunderstood what this was about, didn't I. You're proposing a simple rename, to keep the configuration name simple.

**Comment by Brett208** [comment]
No, I was being ambiguous. We are favoring file size in the optimization section while the default is speed. I think I am okay with either selection although I would probably favor switching it to the default?

We are on the same page that there should only be one Release configuration, so I don't see any reason to give it a special name.
